#include "SoundResource.h"

/* 빠른 아르페지오와 상승 진행으로 만든 웅장한 크레딧 루프. */
static const SoundStep steps[] =
{
    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_LA,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_DO, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_MI, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_LA, SOUND_DELAY_NORMAL},

    {SOUND_NOTE_LOW_FA,  SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_FA,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_LA,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_DO, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_FA, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_LA, SOUND_DELAY_NORMAL},

    {SOUND_NOTE_LOW_SOL, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_RE,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_SOL,     SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_SI,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_RE, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_SOL,SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_SI, SOUND_DELAY_NORMAL},

    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_LA,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_DO, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_MI, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_LA, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_SI, SOUND_DELAY_NORMAL},

    /* 절정 뒤 빠르게 하강하여 다음 루프의 저음으로 연결한다. */
    {SOUND_NOTE_HIGH_LA, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_SOL,SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_FA, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_MI, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_RE, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_HIGH_DO, SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_SI,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_LA,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_VERY_SHORT},
    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_LONG},
};

const SoundSequence creditBgm =
{
    steps,
    SOUND_STEP_COUNT(steps),
    true,
};
