#include "SoundResource.h"

/* 낮은 반복음 위에 상승 구간을 얹은 두더지 게임용 긴장감 있는 루프. */
static const SoundStep steps[] =
{
    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_SHORT},
    {SOUND_NOTE_REST,    SOUND_DELAY_SHORT},
    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_SHORT},

    {SOUND_NOTE_RE,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_NORMAL},
    {SOUND_NOTE_REST,    SOUND_DELAY_SHORT},

    {SOUND_NOTE_LOW_SOL, SOUND_DELAY_SHORT},
    {SOUND_NOTE_REST,    SOUND_DELAY_SHORT},
    {SOUND_NOTE_LOW_SOL, SOUND_DELAY_SHORT},
    {SOUND_NOTE_LOW_SI,  SOUND_DELAY_SHORT},

    {SOUND_NOTE_RE,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_RE,      SOUND_DELAY_NORMAL},
    {SOUND_NOTE_REST,    SOUND_DELAY_SHORT},

    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_RE,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_SHORT},

    {SOUND_NOTE_FA,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_RE,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_DO,      SOUND_DELAY_SHORT},

    {SOUND_NOTE_LOW_SI,  SOUND_DELAY_SHORT},
    {SOUND_NOTE_RE,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_FA,      SOUND_DELAY_SHORT},
    {SOUND_NOTE_MI,      SOUND_DELAY_SHORT},

    {SOUND_NOTE_RE,      SOUND_DELAY_NORMAL},
    {SOUND_NOTE_LOW_LA,  SOUND_DELAY_NORMAL},
};

const SoundSequence inGameBgm =
{
    steps,
    SOUND_STEP_COUNT(steps),
    true,
};
